name: deposit
repository: https://github.com/bluefireteam/deposit

packages:
  - packages/**

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

scripts:
  pub:
    run: melos exec -c 10 dart pub get
    description: Run all static analysis checks.

  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    run: |
      melos exec -c 10 dart analyze --fatal-infos
    select-package:
      file-exists:
        - analysis_options.yaml
    description: Run `dart analyze` for all packages.

  format:
    run: melos exec dart format .
    description: Run `dart format` for all packages.
  
  format:ci:
    run: melos exec dart format --set-exit-if-changed .
    description: Run `dart format` for all packages and set exit if it is incorrectly formatted.

  dartdoc:
    run: |
      melos exec rm -rf doc/
      melos exec dartdoc --no-auto-include-dependencies --quiet
    select-package:
      file-exists:
        - dartdoc_options.yaml
    description: Run `dartdoc` for all packages.

  test:
    run: melos run test:select --no-select
    description: Run all Dart tests in this project.

  test:select:
    run: melos exec dart test
    select-package:
      dir-exists:
        - test
    description: Run `dart test` for selected packages.

  test:coverage:
    run: |
      melos exec dart test --coverage coverage/
      melos exec dart run coverage:format_coverage -i coverage/test/ --lcov --out coverage/lcov.info --packages .packages --report-on lib
      melos exec genhtml coverage/lcov.info --output-directory=coverage/
    select-package:
      dir-exists: test
    description: Generate HTML coverage for all the packages.

  test:coverage:lcov:
    run: |
      melos exec dart test --coverage coverage/
      melos exec dart run coverage:format_coverage -i coverage/test/ --lcov --out ../../coverage/package_\$MELOS_PACKAGE_NAME.info --packages .packages --report-on lib
      tracefiles=""
      for file in $(pwd)/coverage/package_*.info; do
        sed -i "s|SF:$(pwd)/packages/\([a-z_]*\)/\(.*\)|SF:\1 \2|g" $file
        tracefiles="$tracefiles --add-tracefile $file"
      done
      lcov $(echo $tracefiles) --output-file coverage/lcov_combined.info; 
      lcov --list coverage/lcov_combined.info
    select-package:
      dir-exists: test
    description: Generate LCOV coverage for all the packages as a single LCOV file.
