name: deposit
description: A data backend agnostic repository pattern package for Dart
version: 1.0.0
homepage: https://github.com/bluefireteam/deposit

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  test: ^1.20.1
  very_good_analysis: ^2.4.0
